language: php

php:
  - 7.0

before_script:
  - nvm install 6
  - npm install

before_install:
  # Mock mail services
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix

before_script:
  # Mock mail service
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" 127.0.0.1:2500 1000 &
  - echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' | sudo tee "/home/travis/.phpenv/versions/`php -i | grep "PHP Version" | head -n 1 | grep -o -P '\d+\.\d+\.\d+.*'`/etc/conf.d/sendmail.ini"

matrix:
  fast_finish: true

script:
  - npm install bower -g
  - npm install gulp -g
  - make test-all

after_success:
  - make coveralls
