language: php

php:
  - 5.6
  - 7.0

before_install:
  - sudo apt-get install nodejs-legacy
  - sudo apt-get install npm

matrix:
  fast_finish: true

script:
  - make test-all

after_script:
  - make coveralls